# GNU Makefile

CFLAGS = -Wall -g -lm

CharPointFunc = strcat strend
PointFuncArgs = getint getfloat

all: $(PointFuncArgs) $(CharPointFunc)

strend:
strcat:
getfloat:
getint:

.PHONY: clean
clean:
	rm -f *~ *.o
