# GNU Makefile

CFLAGS = -Wall -g -lm

CPreProcessor = swap
Recursion = itoa_r reverse_r
StaticVars = static
ExtVars = polish modulus stack math variables ungets one eof line
RetNonInt = atof
Basics = index

all: $(Basics) $(RetNonInt) $(ExtVars) $(StaticVars) $(Recursion) $(CPreProcessor)

swap:
reverse_r:
itoa_r:
static:
line:
eof:
one:
ungets:
variables:
math:
stack:
modulus:
polish:
atof:
index:


.PHONY: clean
clean:
	rm -f *~ *.o
