# GNU Makefile

CFLAGS = -Wall -g -lm

ExtVars = polish modulus stack math variables ungets one eof line
RetNonInt = atof
Basics = index

all: $(Basics) $(RetNonInt) $(ExtVars)

line:
eof:
one:
ungets:
variables:
math:
stack:
modulus:
polish:
atof:
index:


.PHONY: clean
clean:
	rm -f *~ *.o
