# Makefile

CFLAGS = -Wall -g

ExtVarsScope = detab entab foldline
CharArrays = longestline longestlinelen eightycharsormore \
              trimwhitespace reverseline
Functions = tempconvwithfunc
Arrays =  wordhisto charfreqhisto
CharInOut = in2out in2outcompact verifybool valueofeof whitespace \
             oneblank subtbbs wordcount onewordperline
SymbolicConstants = tempconvdef 
ForStatement = tempconvfor
VarsAndArithExprs = tempconv tempconvfloat tempconvhead tempcel2fahr
GettingStarted = hello helloc

all: $(GettingStarted) $(VarsAndArithExprs) $(ForStatement) \
      $(SymbolicConstants) $(CharInOut) $(Arrays) $(Functions) \
       $(CharArrays) $(ExtVarsScope)

foldline:
entab:
detab:
reverseline:
trimwhitespace:
eightycharsormore:
longestlinelen:
longestline:
tempconvwithfunc:
charfreqhisto:
wordhisto:
onewordperline:
wordcount:
subtbbs:
oneblank:
whitespace: 
valueofeof:
verifybool:
in2outcompact: 
in2out:
tempconvdef:
tempconvfor:
tempcel2fahr:
tempconvhead: 
tempconvfloat:
tempconv:
helloc:
hello:

.PHONY: clean
clean:
	rm -f *~ *.o
