# GNU Makefile

CFLAGS = -Wall -g -lm

ConditionalExps = lower
AssignOpsAndExps = bitcount
BitwiseOperators = setbits invertbits rightrot
IncrementAndDecrementOps = squeeze any
TypeConversions = htoi
RelationalAndLogicalOps = forloop
DataTypesAndSizes = range

all: $(DataTypesAndSizes) $(RelationalAndLogicalOps) $(TypeConversions) \
	$(IncrementAndDecrementOps) $(BitwiseOperators) $(AssignOpsAndExps) \
         $(ConditionalExps)

lower:
bitcount:
rightrot:
invertbits:
setbits:
any:
squeeze:
htoi:
forloop:
range:

.PHONY: clean
clean:
	rm -f *~ *.o
