# GNU Makefile

CFLAGS = -Wall -g -lm

DoWhile = itoa itob itoa3
WhileFor = expand
Switch = escape
ElseIf = binsearch

all: $(ElseIf) $(Switch) $(WhileFor) $(DoWhile)

itoa3:
itob:
itoa:
expand:
escape:
binsearch:

.PHONY: clean
clean:
	rm -f *~ *.o
